version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:331230890924:task-definition/first-run-task-definition:5"
        LoadBalancerInfo:
          ContainerName: "sample-app"
          ContainerPort: 80
